/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallRecord {
  'duration' : bigint,
  'missed' : boolean,
  'callType' : { 'video' : null } |
    { 'voice' : null },
  'timestamp' : bigint,
  'callee' : Principal,
  'caller' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'deleted' : boolean,
  'content' : string,
  'seen' : boolean,
  'sender' : Principal,
  'mediaUrl' : ExternalBlob,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface Profile {
  'bio' : string,
  'blockedUsers' : Array<Principal>,
  'displayName' : string,
  'avatarUrl' : ExternalBlob,
  'lastSeen' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallHistory' : ActorMethod<[], Array<CallRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesWith' : ActorMethod<[Principal], Array<Message>>,
  'getOwnProfile' : ActorMethod<[], Profile>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCall' : ActorMethod<
    [Principal, { 'video' : null } | { 'voice' : null }, bigint, boolean],
    undefined
  >,
  'markMessageSeen' : ActorMethod<[bigint], undefined>,
  'registerOrUpdateProfile' : ActorMethod<
    [string, ExternalBlob, string],
    Profile
  >,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string, ExternalBlob], Message>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];