/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'blockedUsers' : IDL.Vec(IDL.Principal),
  'displayName' : IDL.Text,
  'avatarUrl' : ExternalBlob,
  'lastSeen' : IDL.Int,
});
export const CallRecord = IDL.Record({
  'duration' : IDL.Nat,
  'missed' : IDL.Bool,
  'callType' : IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null }),
  'timestamp' : IDL.Int,
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
});
export const Message = IDL.Record({
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'seen' : IDL.Bool,
  'sender' : IDL.Principal,
  'mediaUrl' : ExternalBlob,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallHistory' : IDL.Func([], [IDL.Vec(CallRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesWith' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getOwnProfile' : IDL.Func([], [Profile], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCall' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null }),
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'markMessageSeen' : IDL.Func([IDL.Nat], [], []),
  'registerOrUpdateProfile' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [Profile],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, ExternalBlob],
      [Message],
      [],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'blockedUsers' : IDL.Vec(IDL.Principal),
    'displayName' : IDL.Text,
    'avatarUrl' : ExternalBlob,
    'lastSeen' : IDL.Int,
  });
  const CallRecord = IDL.Record({
    'duration' : IDL.Nat,
    'missed' : IDL.Bool,
    'callType' : IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null }),
    'timestamp' : IDL.Int,
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
  });
  const Message = IDL.Record({
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'seen' : IDL.Bool,
    'sender' : IDL.Principal,
    'mediaUrl' : ExternalBlob,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallHistory' : IDL.Func([], [IDL.Vec(CallRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOwnProfile' : IDL.Func([], [Profile], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCall' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null }),
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'markMessageSeen' : IDL.Func([IDL.Nat], [], []),
    'registerOrUpdateProfile' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [Profile],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, ExternalBlob],
        [Message],
        [],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };